maintainer       'Biola University'
maintainer_email 'adam.crownoble@biola.edu'
description      'Installs Oracle Instant Client'
version          '0.2.0'
recipe           'oracle_instant_client', 'Installs Oracle Instant Client libraries'
supports         'ubuntu'
