name             'zfs_linux'
maintainer       'Biola University'
maintainer_email 'troy.ready@biola.edu'
license          'Apache 2.0'
description      'Installs/Configures zfs on linux'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '1.4.0'
depends          'apt'
depends          'cron'
depends          'ark'
supports         'ubuntu'
supports         'centos'
