maintainer       "Biola University"
maintainer_email "jared.king@biola.edu"
license          "Apache 2.0"
description      "Installs/Configures vsftpd"
version          "0.0.1"
supports 				 "ubuntu", "12.04"
