maintainer       'Biola'
maintainer_email 'adam.crownoble@biola.edu'
description      'Installs Phusion Passenger and Nginx with RVM'
version          '0.1.0'
depends          'rvm'
recipe           'passenger_biola', 'Installs Phusion Passenger and Nginx with RVM'
supports         'ubuntu'