maintainer       'Biola'
maintainer_email 'adam.crownoble@biola.edu'
description      'Installs a sidekiq Upstart script'
version          '0.2.0'
recipe           'sidekiq_biola', 'Installs a sidekiq Upstart script'
supports         'ubuntu'
