maintainer       "Biola University"
maintainer_email "jared.king@biola.edu"
license          "Apache 2.0"
description      "Installs dnsmasq to provide DNS caching"
version          "1.0.0"
depends          "resolver"
