maintainer       'Biola'
maintainer_email 'adam.crownoble@biola.edu'
description      'Various configurations to support serving Ruby apps'
version          '0.4.0'
depends          'logrotate'
recipe           'ruby_app', 'Various configurations to support serving Ruby apps'
supports         'ubuntu'
