maintainer       "Biola University"
maintainer_email "jared.king@biola.edu"
license          "Apache 2.0"
description      "Cookbook for modifying specific registry settings"
version          "0.0.1"
supports 				 "Windows"